/** @type {import('tailwindcss').Config} */

const rgb = (token) => `rgb(var(--color-${token}) / <alpha-value>)`;

// Semantic colors → CSS variables in app/globals.css (:root + [data-theme="light"])
const colors = {
  surface: rgb("surface"),
  "surface-container-lowest": rgb("surface-container-lowest"),
  "surface-container-low": rgb("surface-container-low"),
  "surface-container": rgb("surface-container"),
  "surface-container-high": rgb("surface-container-high"),
  "surface-container-highest": rgb("surface-container-highest"),
  "surface-bright": rgb("surface-bright"),
  "surface-dim": rgb("surface-dim"),
  "surface-variant": rgb("surface-variant"),
  "surface-tint": rgb("surface-tint"),
  primary: rgb("primary"),
  "primary-fixed": rgb("primary-fixed"),
  "primary-fixed-dim": rgb("primary-fixed-dim"),
  "primary-container": rgb("primary-container"),
  "on-primary": rgb("on-primary"),
  "on-primary-fixed": rgb("on-primary-fixed"),
  "on-primary-fixed-variant": rgb("on-primary-fixed-variant"),
  "on-primary-container": rgb("on-primary-container"),
  "inverse-primary": rgb("inverse-primary"),
  secondary: rgb("secondary"),
  "secondary-fixed": rgb("secondary-fixed"),
  "secondary-fixed-dim": rgb("secondary-fixed-dim"),
  "secondary-container": rgb("secondary-container"),
  "on-secondary": rgb("on-secondary"),
  "on-secondary-fixed": rgb("on-secondary-fixed"),
  "on-secondary-fixed-variant": rgb("on-secondary-fixed-variant"),
  "on-secondary-container": rgb("on-secondary-container"),
  tertiary: rgb("tertiary"),
  "tertiary-fixed": rgb("tertiary-fixed"),
  "tertiary-fixed-dim": rgb("tertiary-fixed-dim"),
  "tertiary-container": rgb("tertiary-container"),
  "on-tertiary": rgb("on-tertiary"),
  "on-tertiary-fixed": rgb("on-tertiary-fixed"),
  "on-tertiary-fixed-variant": rgb("on-tertiary-fixed-variant"),
  "on-tertiary-container": rgb("on-tertiary-container"),
  background: rgb("background"),
  "on-background": rgb("on-background"),
  "on-surface": rgb("on-surface"),
  "on-surface-variant": rgb("on-surface-variant"),
  "inverse-surface": rgb("inverse-surface"),
  "inverse-on-surface": rgb("inverse-on-surface"),
  outline: rgb("outline"),
  "outline-variant": rgb("outline-variant"),
  frost: "var(--frost)",
  "frost-variant": "var(--frost-variant)",
  error: rgb("error"),
  "error-container": rgb("error-container"),
  "on-error": rgb("on-error"),
  "on-error-container": rgb("on-error-container"),
  "auth-modal-ink": rgb("auth-modal-ink"),
};

module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors,
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        round: "9999px",
      },
      fontFamily: {
        sans: ["'Inter'", "system-ui", "sans-serif"],
        headline: ["'Inter'", "system-ui", "sans-serif"],
        body: ["'Inter'", "system-ui", "sans-serif"],
        label: ["'Inter'", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      backgroundImage: {
        "primary-gradient": "var(--bg-primary-gradient)",
        "primary-gradient-rtl": "var(--bg-primary-gradient-rtl)",
        "primary-gradient-ttb": "var(--bg-primary-gradient-ttb)",
        "auth-pulse-lg": "var(--bg-auth-pulse-lg)",
        "auth-pulse-sm": "var(--bg-auth-pulse-sm)",
      },
      boxShadow: {
        ambient: "var(--shadow-ambient)",
        float: "var(--shadow-float)",
        glow: "var(--shadow-glow)",
        "scan-line": "var(--shadow-scan-line)",
        primary: "var(--shadow-primary)",
        "ring-frost": "var(--shadow-ring-frost)",
      },
      animation: {
        scan: "scanAnim 3s linear infinite",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        breathe: "breathe 6s ease-in-out infinite",
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
        aurora: "aurora 60s linear infinite",
      },
      keyframes: {
        scanAnim: {
          "0%": { top: "20%", opacity: "0" },
          "50%": { opacity: "1" },
          "100%": { top: "80%", opacity: "0" },
        },
        breathe: {
          "0%, 100%": { opacity: "0.6", transform: "scale(1)" },
          "50%": { opacity: "1", transform: "scale(1.05)" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        aurora: {
          from: {
            backgroundPosition: "50% 50%, 50% 50%",
          },
          to: {
            backgroundPosition: "350% 50%, 350% 50%",
          },
        },
      },
    },
  },
  plugins: [],
};
